"""In-memory dummy data for Phase 1 of the commercial control app."""

from __future__ import annotations

from copy import deepcopy

PROJECT_METADATA = {
    "name": "Aurora Residence",
    "type": "Mixed-use Apartment",
    "location": "Jakarta",
    "client_type": "Property Developer",
    "currency": "IDR",
}


PACKAGE_DATA = [
    {
        "package": "Earthwork",
        "contractor": "PT Cipta Galian Nusantara",
        "contract_number": "AR-EW-001",
        "package_status": "Ongoing",
        "procurement_status": "Contract Signed",
        "remarks": "Bulk excavation and disposal progressing on main tower zone.",
        "original_budget": 12_500_000_000,
        "contract_award": 11_900_000_000,
        "approved_vo": 250_000_000,
        "pending_vo": 150_000_000,
        "certified_payment": 7_100_000_000,
    },
    {
        "package": "Foundation",
        "contractor": "PT Pondasi Prima Konstruksi",
        "contract_number": "AR-FDN-002",
        "package_status": "Ongoing",
        "procurement_status": "Contract Signed",
        "remarks": "Bored pile works substantially complete; pile cap works ongoing.",
        "original_budget": 38_000_000_000,
        "contract_award": 37_200_000_000,
        "approved_vo": 1_100_000_000,
        "pending_vo": 550_000_000,
        "certified_payment": 22_800_000_000,
    },
    {
        "package": "Structure",
        "contractor": "PT Beton Karya Utama",
        "contract_number": "AR-STR-003",
        "package_status": "Awarded",
        "procurement_status": "Contract Signed",
        "remarks": "Main contract awarded; mobilization and shop drawings in progress.",
        "original_budget": 95_000_000_000,
        "contract_award": 93_750_000_000,
        "approved_vo": 2_600_000_000,
        "pending_vo": 1_450_000_000,
        "certified_payment": 49_500_000_000,
    },
    {
        "package": "Architecture",
        "contractor": "PT Arsitek Finishing Mandiri",
        "contract_number": "AR-ARC-004",
        "package_status": "Tendering",
        "procurement_status": "Under Evaluation",
        "remarks": "Tender clarifications closed; commercial evaluation ongoing.",
        "original_budget": 58_000_000_000,
        "contract_award": 56_500_000_000,
        "approved_vo": 1_900_000_000,
        "pending_vo": 650_000_000,
        "certified_payment": 18_250_000_000,
    },
    {
        "package": "MEP",
        "contractor": "PT Prima Daya MEP",
        "contract_number": "AR-MEP-005",
        "package_status": "Tendering",
        "procurement_status": "Tender Issued",
        "remarks": "Tender issued to shortlisted MEP contractors.",
        "original_budget": 72_500_000_000,
        "contract_award": 70_800_000_000,
        "approved_vo": 1_250_000_000,
        "pending_vo": 2_100_000_000,
        "certified_payment": 21_700_000_000,
    },
    {
        "package": "External Works",
        "contractor": "PT Lanskap Kota Sejahtera",
        "contract_number": "AR-EXT-006",
        "package_status": "Not Started",
        "procurement_status": "Tender Preparation",
        "remarks": "Scope and drawings being coordinated with landscape consultant.",
        "original_budget": 24_000_000_000,
        "contract_award": 23_300_000_000,
        "approved_vo": 450_000_000,
        "pending_vo": 200_000_000,
        "certified_payment": 8_750_000_000,
    },
    {
        "package": "Preliminaries",
        "contractor": "PT Aurora Site Services",
        "contract_number": "AR-PREL-007",
        "package_status": "Ongoing",
        "procurement_status": "Awarded",
        "remarks": "Site facilities, security, and temporary utilities active.",
        "original_budget": 18_000_000_000,
        "contract_award": 17_500_000_000,
        "approved_vo": 800_000_000,
        "pending_vo": 300_000_000,
        "certified_payment": 11_200_000_000,
    },
]


VO_DATA = [
    {
        "vo_no": "VO-001",
        "package": "Earthwork",
        "description": "Additional unsuitable material disposal",
        "vo_status": "Approved",
        "submitted_amount": 300_000_000,
        "approved_amount": 250_000_000,
        "pending_amount": 0,
        "remarks": "Approved after joint site measurement.",
    },
    {
        "vo_no": "VO-002",
        "package": "Earthwork",
        "description": "Temporary haul road extension",
        "vo_status": "Pending",
        "submitted_amount": 150_000_000,
        "approved_amount": 0,
        "pending_amount": 150_000_000,
        "remarks": "Awaiting QS recommendation.",
    },
    {
        "vo_no": "VO-003",
        "package": "Foundation",
        "description": "Additional pile length due to soil condition",
        "vo_status": "Approved",
        "submitted_amount": 1_250_000_000,
        "approved_amount": 1_100_000_000,
        "pending_amount": 0,
        "remarks": "Approved under geotechnical instruction.",
    },
    {
        "vo_no": "VO-004",
        "package": "Foundation",
        "description": "Pile cap rebar congestion mitigation",
        "vo_status": "Under Review",
        "submitted_amount": 550_000_000,
        "approved_amount": 0,
        "pending_amount": 550_000_000,
        "remarks": "Engineer review in progress.",
    },
    {
        "vo_no": "VO-005",
        "package": "Structure",
        "description": "Podium transfer beam strengthening",
        "vo_status": "Approved",
        "submitted_amount": 2_800_000_000,
        "approved_amount": 2_600_000_000,
        "pending_amount": 0,
        "remarks": "Approved with revised structural drawings.",
    },
    {
        "vo_no": "VO-006",
        "package": "Structure",
        "description": "Additional temporary works for ramp access",
        "vo_status": "Pending",
        "submitted_amount": 1_450_000_000,
        "approved_amount": 0,
        "pending_amount": 1_450_000_000,
        "remarks": "Commercial substantiation requested.",
    },
    {
        "vo_no": "VO-007",
        "package": "Architecture",
        "description": "Lobby stone finish upgrade",
        "vo_status": "Approved",
        "submitted_amount": 2_050_000_000,
        "approved_amount": 1_900_000_000,
        "pending_amount": 0,
        "remarks": "Client upgrade instruction approved.",
    },
    {
        "vo_no": "VO-008",
        "package": "Architecture",
        "description": "Revised facade access panels",
        "vo_status": "Under Review",
        "submitted_amount": 650_000_000,
        "approved_amount": 0,
        "pending_amount": 650_000_000,
        "remarks": "Design team response pending.",
    },
    {
        "vo_no": "VO-009",
        "package": "MEP",
        "description": "Generator capacity enhancement",
        "vo_status": "Approved",
        "submitted_amount": 1_400_000_000,
        "approved_amount": 1_250_000_000,
        "pending_amount": 0,
        "remarks": "Approved subject to procurement savings review.",
    },
    {
        "vo_no": "VO-010",
        "package": "MEP",
        "description": "Additional EV charging infrastructure",
        "vo_status": "Submitted",
        "submitted_amount": 2_100_000_000,
        "approved_amount": 0,
        "pending_amount": 2_100_000_000,
        "remarks": "Submitted for client commercial review.",
    },
    {
        "vo_no": "VO-011",
        "package": "External Works",
        "description": "Drainage tie-in revision",
        "vo_status": "Approved",
        "submitted_amount": 500_000_000,
        "approved_amount": 450_000_000,
        "pending_amount": 0,
        "remarks": "Approved following authority coordination.",
    },
    {
        "vo_no": "VO-012",
        "package": "External Works",
        "description": "Additional landscape lighting conduits",
        "vo_status": "Pending",
        "submitted_amount": 200_000_000,
        "approved_amount": 0,
        "pending_amount": 200_000_000,
        "remarks": "Pending lighting consultant confirmation.",
    },
    {
        "vo_no": "VO-013",
        "package": "Preliminaries",
        "description": "Extended tower crane rental",
        "vo_status": "Approved",
        "submitted_amount": 850_000_000,
        "approved_amount": 800_000_000,
        "pending_amount": 0,
        "remarks": "Approved due to revised structural sequence.",
    },
    {
        "vo_no": "VO-014",
        "package": "Preliminaries",
        "description": "Additional site welfare facilities",
        "vo_status": "Under Review",
        "submitted_amount": 300_000_000,
        "approved_amount": 0,
        "pending_amount": 300_000_000,
        "remarks": "Awaiting PM approval.",
    },
]


CLAIM_DATA = [
    {
        "claim_no": "PC-001",
        "period": "2026-01",
        "package": "Earthwork",
        "contractor": "PT Cipta Galian Nusantara",
        "claim_status": "Paid",
        "submitted_amount": 3_800_000_000,
        "certified_amount": 3_600_000_000,
        "payment_amount": 3_600_000_000,
        "remarks": "Certified for excavation and disposal progress.",
    },
    {
        "claim_no": "PC-002",
        "period": "2026-02",
        "package": "Earthwork",
        "contractor": "PT Cipta Galian Nusantara",
        "claim_status": "Certified",
        "submitted_amount": 3_700_000_000,
        "certified_amount": 3_500_000_000,
        "payment_amount": 0,
        "remarks": "Payment recommendation issued.",
    },
    {
        "claim_no": "PC-003",
        "period": "2026-01",
        "package": "Foundation",
        "contractor": "PT Pondasi Prima Konstruksi",
        "claim_status": "Paid",
        "submitted_amount": 12_500_000_000,
        "certified_amount": 12_000_000_000,
        "payment_amount": 12_000_000_000,
        "remarks": "Certified for piling works.",
    },
    {
        "claim_no": "PC-004",
        "period": "2026-02",
        "package": "Foundation",
        "contractor": "PT Pondasi Prima Konstruksi",
        "claim_status": "Certified",
        "submitted_amount": 11_200_000_000,
        "certified_amount": 10_800_000_000,
        "payment_amount": 0,
        "remarks": "Pile cap progress certified.",
    },
    {
        "claim_no": "PC-005",
        "period": "2026-03",
        "package": "Structure",
        "contractor": "PT Beton Karya Utama",
        "claim_status": "Paid",
        "submitted_amount": 25_600_000_000,
        "certified_amount": 24_500_000_000,
        "payment_amount": 24_500_000_000,
        "remarks": "Lower podium works certified and paid.",
    },
    {
        "claim_no": "PC-006",
        "period": "2026-04",
        "package": "Structure",
        "contractor": "PT Beton Karya Utama",
        "claim_status": "Under Review",
        "submitted_amount": 26_200_000_000,
        "certified_amount": 25_000_000_000,
        "payment_amount": 0,
        "remarks": "Upper podium quantities under QS review.",
    },
    {
        "claim_no": "PC-007",
        "period": "2026-04",
        "package": "Architecture",
        "contractor": "PT Arsitek Finishing Mandiri",
        "claim_status": "Certified",
        "submitted_amount": 9_600_000_000,
        "certified_amount": 9_250_000_000,
        "payment_amount": 0,
        "remarks": "Mock-up and early procurement certified.",
    },
    {
        "claim_no": "PC-008",
        "period": "2026-05",
        "package": "Architecture",
        "contractor": "PT Arsitek Finishing Mandiri",
        "claim_status": "Submitted",
        "submitted_amount": 9_200_000_000,
        "certified_amount": 9_000_000_000,
        "payment_amount": 0,
        "remarks": "Wall and floor finishes claim submitted.",
    },
    {
        "claim_no": "PC-009",
        "period": "2026-05",
        "package": "MEP",
        "contractor": "PT Prima Daya MEP",
        "claim_status": "Certified",
        "submitted_amount": 11_300_000_000,
        "certified_amount": 10_700_000_000,
        "payment_amount": 0,
        "remarks": "First fix MEP progress certified.",
    },
    {
        "claim_no": "PC-010",
        "period": "2026-06",
        "package": "MEP",
        "contractor": "PT Prima Daya MEP",
        "claim_status": "Under Review",
        "submitted_amount": 11_400_000_000,
        "certified_amount": 11_000_000_000,
        "payment_amount": 0,
        "remarks": "Testing documentation under review.",
    },
    {
        "claim_no": "PC-011",
        "period": "2026-06",
        "package": "External Works",
        "contractor": "PT Lanskap Kota Sejahtera",
        "claim_status": "Paid",
        "submitted_amount": 4_500_000_000,
        "certified_amount": 4_250_000_000,
        "payment_amount": 4_250_000_000,
        "remarks": "Drainage and road base works paid.",
    },
    {
        "claim_no": "PC-012",
        "period": "2026-07",
        "package": "External Works",
        "contractor": "PT Lanskap Kota Sejahtera",
        "claim_status": "Certified",
        "submitted_amount": 4_750_000_000,
        "certified_amount": 4_500_000_000,
        "payment_amount": 0,
        "remarks": "Landscape sub-base certified.",
    },
    {
        "claim_no": "PC-013",
        "period": "2026-01",
        "package": "Preliminaries",
        "contractor": "PT Aurora Site Services",
        "claim_status": "Paid",
        "submitted_amount": 5_900_000_000,
        "certified_amount": 5_600_000_000,
        "payment_amount": 5_600_000_000,
        "remarks": "Site establishment and temporary utilities paid.",
    },
    {
        "claim_no": "PC-014",
        "period": "2026-02",
        "package": "Preliminaries",
        "contractor": "PT Aurora Site Services",
        "claim_status": "Certified",
        "submitted_amount": 5_900_000_000,
        "certified_amount": 5_600_000_000,
        "payment_amount": 0,
        "remarks": "Monthly site running cost certified.",
    },
]


def get_initial_package_data() -> list[dict]:
    """Return a fresh copy of the initial package data."""
    return deepcopy(PACKAGE_DATA)


def get_initial_vo_data() -> list[dict]:
    """Return a fresh copy of the initial variation order data."""
    return deepcopy(VO_DATA)


def get_initial_claim_data() -> list[dict]:
    """Return a fresh copy of the initial progress claim data."""
    return deepcopy(CLAIM_DATA)
